// GET_ALL_CONTACT //
export const GET_ALL_CONTACT_REQUEST = 'GET_ALL_CONTACT_REQUEST'
export const GET_ALL_CONTACT_SUCCESS = 'GET_ALL_CONTACT_SUCCESS'
export const GET_ALL_CONTACT_FAILED = 'GET_ALL_CONTACT_FAILED'