// GET_ALL_CONTACT //
export const GET_ALL_CONTACT_REQUEST = 'GET_ALL_CONTACT_REQUEST'
export const GET_ALL_CONTACT_SUCCESS = 'GET_ALL_CONTACT_SUCCESS'
export const GET_ALL_CONTACT_FAILED = 'GET_ALL_CONTACT_FAILED'

// ADD_CONTACT //
export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED'

// EDIT_CONTACT //
export const EDIT_CONTACT_REQUEST = 'EDIT_CONTACT_REQUEST'
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS'
export const EDIT_CONTACT_FAILED = 'EDIT_CONTACT_FAILED'